module tile_scheduler #(
    parameter int unsigned TILE_COUNT_WIDTH = 16,
    parameter int unsigned K_TILE_SIZE      = 256,
    parameter int unsigned K_SIZE_WIDTH     = $clog2(K_TILE_SIZE + 1)
) (
    input logic clk,
    input logic reset,

    // ============================================================
    // GEMM command
    //
    // These values are generated by the compiler/runtime.
    // ============================================================

    input logic start,

    input logic [TILE_COUNT_WIDTH-1:0] m_tile_count,
    input logic [TILE_COUNT_WIDTH-1:0] n_tile_count,
    input logic [TILE_COUNT_WIDTH-1:0] k_tile_count,

    // Valid K length of the final K tile.
    //
    // Example:
    // K = 600, K_TILE_SIZE = 256
    //
    // k_tile_count = 3
    // last_k_size  = 88
    //
    input logic [K_SIZE_WIDTH-1:0] last_k_size,


    // ============================================================
    // Tile loader interface
    //
    // Scheduler describes which logical tile is required.
    // The future loader/DMA converts this into memory addresses
    // and handles operand-buffer bank allocation.
    // ============================================================

    output logic a_load_req,
    input  logic a_load_accept,
    input  logic a_load_done,

    output logic b_load_req,
    input  logic b_load_accept,
    input  logic b_load_done,


    // ============================================================
    // A buffer manager - compute side
    // ============================================================

    output logic a_compute_req,
    input  logic a_compute_grant,

    output logic a_compute_done,
    output logic a_release_bank,


    // ============================================================
    // B buffer manager - compute side
    // ============================================================

    output logic b_compute_req,
    input  logic b_compute_grant,

    output logic b_compute_done,
    output logic b_release_bank,


    // ============================================================
    // Matrix controller
    // ============================================================

    output logic matrix_start,
    input  logic matrix_done,

    output logic clear_acc,
    output logic writeback_en,

    output logic [K_SIZE_WIDTH-1:0] current_k_size,


    // ============================================================
    // Current logical tile coordinates
    //
    // A tile = A(m_tile_idx, k_tile_idx)
    // B tile = B(k_tile_idx, n_tile_idx)
    // C tile = C(m_tile_idx, n_tile_idx)
    // ============================================================

    output logic [TILE_COUNT_WIDTH-1:0] m_tile_idx,
    output logic [TILE_COUNT_WIDTH-1:0] n_tile_idx,
    output logic [TILE_COUNT_WIDTH-1:0] k_tile_idx,


    // ============================================================
    // Status
    // ============================================================

    output logic busy,
    output logic done
);


    // ============================================================
    // Types
    // ============================================================

    typedef logic [K_SIZE_WIDTH-1:0] k_size_t;


    typedef enum logic [2:0] {
        ST_IDLE,
        ST_LOAD_REQ,
        ST_WAIT_LOAD,
        ST_ACQUIRE,
        ST_LAUNCH,
        ST_COMPUTE,
        ST_ADVANCE,
        ST_DONE
    } state_t;


    // ============================================================
    // Constants
    // ============================================================

    localparam k_size_t FULL_K_SIZE =
        k_size_t'(K_TILE_SIZE);


    // ============================================================
    // Registers
    // ============================================================

    state_t state;

    logic [TILE_COUNT_WIDTH-1:0] m_tile_count_q;
    logic [TILE_COUNT_WIDTH-1:0] n_tile_count_q;
    logic [TILE_COUNT_WIDTH-1:0] k_tile_count_q;

    k_size_t last_k_size_q;

    logic a_load_issued;
    logic b_load_issued;

    logic a_load_finished;
    logic b_load_finished;

    logic a_acquired;
    logic b_acquired;


    // ============================================================
    // Current tile position
    // ============================================================

    logic first_k_tile;
    logic last_k_tile;
    logic last_n_tile;
    logic last_m_tile;


    assign first_k_tile =
        (k_tile_idx == '0);

    assign last_k_tile =
        (k_tile_count_q != '0) &&
        (k_tile_idx == (k_tile_count_q - 1'b1));

    assign last_n_tile =
        (n_tile_count_q != '0) &&
        (n_tile_idx == (n_tile_count_q - 1'b1));

    assign last_m_tile =
        (m_tile_count_q != '0) &&
        (m_tile_idx == (m_tile_count_q - 1'b1));


    // ============================================================
    // K control
    //
    // First K tile:
    //     clear accumulator
    //
    // Last K tile:
    //     write final C tile
    // ============================================================

    assign clear_acc =
        first_k_tile;

    assign writeback_en =
        last_k_tile;

    assign current_k_size =
        last_k_tile ? last_k_size_q : FULL_K_SIZE;


    // ============================================================
    // Loader requests
    //
    // Hold request until loader accepts it.
    // ============================================================

    assign a_load_req =
        (state == ST_LOAD_REQ) &&
        !a_load_issued;

    assign b_load_req =
        (state == ST_LOAD_REQ) &&
        !b_load_issued;


    // ============================================================
    // Buffer compute requests
    // ============================================================

    assign a_compute_req =
        (state == ST_ACQUIRE) &&
        !a_acquired;

    assign b_compute_req =
        (state == ST_ACQUIRE) &&
        !b_acquired;


    // ============================================================
    // Matrix controller
    // ============================================================

    assign matrix_start =
        (state == ST_LAUNCH);


    // ============================================================
    // Compute completion
    //
    // Phase 1:
    // Always release both operand banks after each K tile.
    //
    // Reuse policy will be added later as an independent layer.
    // ============================================================

    assign a_compute_done =
        (state == ST_COMPUTE) &&
        matrix_done;

    assign b_compute_done =
        (state == ST_COMPUTE) &&
        matrix_done;

    assign a_release_bank = 1'b1;
    assign b_release_bank = 1'b1;


    // ============================================================
    // Status
    // ============================================================

    assign busy =
        (state != ST_IDLE) &&
        (state != ST_DONE);

    assign done =
        (state == ST_DONE);


    // ============================================================
    // Main FSM
    // ============================================================

    always_ff @(posedge clk) begin

        if (reset) begin

            state <= ST_IDLE;

            m_tile_count_q <= '0;
            n_tile_count_q <= '0;
            k_tile_count_q <= '0;

            last_k_size_q <= '0;

            m_tile_idx <= '0;
            n_tile_idx <= '0;
            k_tile_idx <= '0;

            a_load_issued   <= 1'b0;
            b_load_issued   <= 1'b0;

            a_load_finished <= 1'b0;
            b_load_finished <= 1'b0;

            a_acquired <= 1'b0;
            b_acquired <= 1'b0;

        end else begin

            case (state)

                // =================================================
                // IDLE
                //
                // Capture one GEMM command.
                // =================================================

                ST_IDLE: begin

                    if (start) begin

                        m_tile_count_q <= m_tile_count;
                        n_tile_count_q <= n_tile_count;
                        k_tile_count_q <= k_tile_count;

                        last_k_size_q <= last_k_size;

                        m_tile_idx <= '0;
                        n_tile_idx <= '0;
                        k_tile_idx <= '0;

                        a_load_issued   <= 1'b0;
                        b_load_issued   <= 1'b0;

                        a_load_finished <= 1'b0;
                        b_load_finished <= 1'b0;

                        a_acquired <= 1'b0;
                        b_acquired <= 1'b0;

                        state <= ST_LOAD_REQ;

                    end

                end


                // =================================================
                // LOAD REQUEST
                //
                // Current coordinates describe:
                //
                // A(m, k)
                // B(k, n)
                //
                // A and B loaders may accept independently.
                // =================================================

                ST_LOAD_REQ: begin

                    if (a_load_accept) begin
                        a_load_issued <= 1'b1;
                    end

                    if (b_load_accept) begin
                        b_load_issued <= 1'b1;
                    end

                    if (
                        (a_load_issued || a_load_accept) &&
                        (b_load_issued || b_load_accept)
                    ) begin

                        state <= ST_WAIT_LOAD;

                    end

                end


                // =================================================
                // WAIT LOAD
                //
                // Wait until both operand tiles have reached their
                // local operand buffers.
                // =================================================

                ST_WAIT_LOAD: begin

                    if (a_load_done) begin
                        a_load_finished <= 1'b1;
                    end

                    if (b_load_done) begin
                        b_load_finished <= 1'b1;
                    end

                    if (
                        (a_load_finished || a_load_done) &&
                        (b_load_finished || b_load_done)
                    ) begin

                        state <= ST_ACQUIRE;

                    end

                end


                // =================================================
                // ACQUIRE
                //
                // Ask A/B buffer managers for READY compute banks.
                // =================================================

                ST_ACQUIRE: begin

                    if (a_compute_grant) begin
                        a_acquired <= 1'b1;
                    end

                    if (b_compute_grant) begin
                        b_acquired <= 1'b1;
                    end

                    if (
                        (a_acquired || a_compute_grant) &&
                        (b_acquired || b_compute_grant)
                    ) begin

                        state <= ST_LAUNCH;

                    end

                end


                // =================================================
                // LAUNCH
                //
                // matrix_start is asserted for exactly this cycle.
                // =================================================

                ST_LAUNCH: begin

                    state <= ST_COMPUTE;

                end


                // =================================================
                // COMPUTE
                //
                // Matrix controller performs the current K tile.
                // =================================================

                ST_COMPUTE: begin

                    if (matrix_done) begin

                        state <= ST_ADVANCE;

                    end

                end


                // =================================================
                // ADVANCE
                //
                // Implements:
                //
                // for (m)
                //   for (n)
                //     for (k)
                //
                // Output-stationary:
                // Complete all K tiles of one C tile before
                // moving to another C tile.
                // =================================================

                ST_ADVANCE: begin

                    a_load_issued   <= 1'b0;
                    b_load_issued   <= 1'b0;

                    a_load_finished <= 1'b0;
                    b_load_finished <= 1'b0;

                    a_acquired <= 1'b0;
                    b_acquired <= 1'b0;


                    if (!last_k_tile) begin

                        // Next K tile of the same C tile.

                        k_tile_idx <= k_tile_idx + 1'b1;

                        state <= ST_LOAD_REQ;

                    end else begin

                        // Current C tile is complete.

                        k_tile_idx <= '0;


                        if (!last_n_tile) begin

                            // Move to the next output-column tile.

                            n_tile_idx <= n_tile_idx + 1'b1;

                            state <= ST_LOAD_REQ;

                        end else begin

                            n_tile_idx <= '0;


                            if (!last_m_tile) begin

                                // Move to the next output-row tile.

                                m_tile_idx <= m_tile_idx + 1'b1;

                                state <= ST_LOAD_REQ;

                            end else begin

                                // Entire GEMM complete.

                                state <= ST_DONE;

                            end

                        end

                    end

                end


                // =================================================
                // DONE
                //
                // One-cycle completion pulse.
                // =================================================

                ST_DONE: begin

                    state <= ST_IDLE;

                end


                // =================================================
                // Recovery
                // =================================================

                default: begin

                    state <= ST_IDLE;

                end

            endcase

        end

    end


    // ============================================================
    // Parameter checks
    // ============================================================

    initial begin

        if (K_TILE_SIZE < 1) begin
            $fatal(1, "K_TILE_SIZE must be >= 1");
        end

        if (TILE_COUNT_WIDTH < 1) begin
            $fatal(1, "TILE_COUNT_WIDTH must be >= 1");
        end

    end

endmodule
